[package]
name = "chip8rs"
version = "0.1.0"
authors = ["carva"]

[dependencies]
rand = "*"
gfx = "0.13.0"
gfx_device_gl = "0.12.0"
piston2d-gfx_graphics = "0.35.0"
piston2d-graphics = "0.19.0"
pistoncore-input = "0.15.0"
pistoncore-window = "0.24.0"
pistoncore-glutin_window = "0.33.0"
